import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./ui/Navbar";
import Footer from "./ui/Footer";
import { AuthProvider } from "./context/AuthContext";
import { Provider } from "react-redux";
import store from "@/app/redux/store";
import { ProfileProvider } from "./context/ProfileContext";
import { Providers } from "./redux/Providers";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "KidsBank",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="w-full flex flex-col min-h-screen">
          <AuthProvider>
            <ProfileProvider>
              <Providers>
                <Navbar />
                {children}
                <Footer />
              </Providers>
            </ProfileProvider>
          </AuthProvider>
        </div>
      </body>
    </html>
  );
}
